#!/bin/bash

# Statically link against libmusl on Linux:
#
#   sudo apt install musl-dev musl-tools
#   export MUSL_INCLUDE=/tmp
#   git clone https://github.com/sabotage-linux/kernel-headers.git $MUSL_INCLUDE/kernel-headers
#   RESTRICT_PROCESS=seccomp ./musl-make clean all
#
set -o errexit
set -o nounset
set -o pipefail

export MUSL_INCLUDE="${MUSL_INCLUDE-/usr/local/lib}"

MACHTYPE="$(uname -m)"
case "${MACHTYPE}" in
  armv6l) ;&
  armv7l) MACHTYPE=arm ;;
  *) ;;
esac

export CC="musl-gcc -static -Os"
export TREP_LDFLAGS="-I$MUSL_INCLUDE/kernel-headers/generic/include -I$MUSL_INCLUDE/kernel-headers/${MACHTYPE}/include"
export TREP_CFLAGS="-UHAVE_FTS -UHAVE_QUEUE -DHAVE_DECL_MAX ${TREP_CFLAGS-}"
exec make $@
